# Generated by Django 4.2.7 on 2023-11-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('timeStamp', models.DateTimeField()),
                ('loadId', models.IntegerField()),
                ('ogLatitude', models.FloatField()),
                ('ogLongtitude', models.FloatField()),
                ('destLatitude', models.FloatField()),
                ('destLongitude', models.FloatField()),
                ('eqType', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('mileage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('truckId', models.IntegerField()),
                ('timeStamp', models.DateTimeField()),
                ('posLatitude', models.FloatField()),
                ('posLongitude', models.FloatField()),
                ('eqType', models.CharField(max_length=100)),
                ('nextTripPref', models.CharField(choices=[('ln', 'LONG'), ('sh', 'SHORT')], max_length=2)),
                ('lastnotified', models.DateTimeField()),
                ('idleTime', models.IntegerField()),
            ],
        ),
    ]
