# Generated by Django 4.2.7 on 2023-11-18 23:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('seq', models.IntegerField()),
                ('timeStamp', models.DateTimeField()),
                ('loadId', models.IntegerField(primary_key=True, serialize=False)),
                ('ogLatitude', models.FloatField()),
                ('ogLongitude', models.FloatField()),
                ('destLatitude', models.FloatField()),
                ('destLongitude', models.FloatField()),
                ('eqType', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('mileage', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('truckId', models.IntegerField()),
                ('loadId', models.IntegerField()),
                ('timeSent', models.DateTimeField()),
                ('message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('seq', models.IntegerField()),
                ('truckId', models.IntegerField(primary_key=True, serialize=False)),
                ('timeStamp', models.DateTimeField()),
                ('posLatitude', models.FloatField()),
                ('posLongitude', models.FloatField()),
                ('eqType', models.CharField(max_length=100)),
                ('nextTripPref', models.CharField(choices=[('ln', 'LONG'), ('sh', 'SHORT')], max_length=2)),
                ('lastnotified', models.DateTimeField()),
                ('idleTime', models.IntegerField()),
            ],
        ),
    ]
