# Generated by Django 4.2.7 on 2023-11-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loadid', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('price', models.FloatField()),
                ('mileage', models.FloatField()),
                ('type', models.CharField(choices=[('VN', 'VAN'), ('FB', 'FLATBED'), ('RF', 'REEFER')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trucker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truckerid', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('lastnotified', models.DateTimeField(verbose_name='last notified')),
                ('type', models.CharField(choices=[('VN', 'VAN'), ('FB', 'FLATBED'), ('RF', 'REEFER')], max_length=2)),
                ('pref', models.CharField(choices=[('ln', 'LONG'), ('sh', 'SHORT')], max_length=2)),
            ],
        ),
    ]
