# Generated by Django 4.2.7 on 2023-11-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='load',
            name='id',
        ),
        migrations.RemoveField(
            model_name='truck',
            name='id',
        ),
        migrations.AlterField(
            model_name='load',
            name='loadId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truckId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
