# Generated by Django 4.2.7 on 2023-11-18 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('road_data', '0002_remove_load_id_remove_truck_id_alter_load_loadid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='load',
            name='eqType',
            field=models.CharField(choices=[('vn', 'Van'), ('rf', 'Reefer'), ('fb', 'FlatBed')], max_length=2),
        ),
        migrations.AlterField(
            model_name='truck',
            name='eqType',
            field=models.CharField(choices=[('vn', 'Van'), ('rf', 'Reefer'), ('fb', 'FlatBed')], max_length=2),
        ),
    ]
